name: Update Wiki

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: publish-to-git
      uses: seanmiddleditch/gha-publish-to-git@v1
      with:
        repository: sarathm09/vibranium.wiki
        branch: master
        github_pat: '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'
        source_folder: docs
